server {
    listen 80;
    server_name localhost;

    # Flux REST standard (Health check, Docs)
    location / {
        proxy_pass http://trading-api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Configuration CRITIQUE pour maintenir le WebSocket du Broker ouvert
    location /ws/ {
        proxy_pass http://trading-api:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400s; # Laisse la connexion ouverte pendant 24h
    }
}